name: Update README with Snake Animation

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update README
        run: echo '![Snake animation](.github/workflows/github-snake.svg)' >> README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "douglaskforbes@gmail.com"
          git config --local user.name "DougKF"
          git add README.md
          git commit -m "Update README with Snake Animation"
          git remote add origin-with-token "https://${{ secrets.GH_TOKEN }}@github.com/Dug-F/Dug-F.git"
          git push origin-with-token main
